# General Travis config
sudo: required
services:
  - docker
language: python
python: # Only one version for now
    - "2.7"
cache: pip

# Installation of the system
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
install: tests/install.sh
script: tests/${TEST}

# Test matrix will be constructed from here. Listing out each set of tests
# to execute will permit them to be executed in parallel
env:
    - TEST=lint.sh
    - TEST=docs.sh
    - TEST=cent6_slave.sh
    - TEST=cent7_slave.sh
