- name: configure certificate authority, if necessary
  hosts: certificate_authority
  gather_facts: false
  roles:
    - certificate_authority

- name: configure repositories
  hosts: repositories
  roles:
    - repositories

- name: configure jenkins masters
  hosts: jenkins_master
  roles:
    - jenkins_master

- name: configure jenkins slaves
  become: true
  hosts: jenkins_slave
  roles:
    - jenkins_slave
