- name: wait for Jenkins to start up
  wait_for:
    port: "{{ https_enabled | ternary(443, 80) }}"
    state: started
    delay: 15

- name: download jenkins CLI
  get_url:
    url: "{{ https_enabled | ternary('https', 'http') }}://localhost/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_home }}/jenkins-cli.jar"
    force: true
    validate_certs: false
  become_user: jenkins
  become: true

- name: configure CLI users appropriately
  jenkins_cli_user:
    jenkins_home: "{{ jenkins_home }}"
    key_file: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
