- name: check if swarm connected to the master with systemd
  command: systemctl status swarm
  ignore_errors: yes
  changed_when: false
  register: service_swarm_status

- name: grab errors for the last run of the systemd swarm service
  shell: >
    journalctl --no-pager -u swarm -o cat
    _PID=$(systemctl show swarm --property=ExecMainPID
    | cut -d '=' -f 2)
  register: service_swarm_err_output
  when: service_swarm_status|failed

- name: report errors for systemd swarm service
  include: check_swarm_errors.yml
  when: service_swarm_status|failed
