- name: ensure keystore directory exists
  file:
    path: "{{ jenkins_home }}/.ssl"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy in ssl files
  copy:
    src: "{{ item.in }}"
    dest: "{{ jenkins_home }}/.ssl/{{ item.out }}"
    owner: jenkins
    group: jenkins
    mode: 0755
  with_items:
    - in: "{{ jenkins_ssl_cert }}"
      out: jenkins.crt
    - in: "{{ jenkins_ssl_key }}"
      out: jenkins.key

- name: copy ssl certificate to anchors
  copy:
    src: "{{ jenkins_ssl_cert }}"
    dest: /etc/pki/ca-trust/source/anchors/jenkins.crt
    owner: root
    group: root
  notify: update certificate chains

- name: configuring httpd to forward port 80 traffic to port 443
  lineinfile:
    line: "{{ item }}"
    dest: /etc/httpd/conf/httpd.conf
    state: present
  with_items:
    - RewriteEngine On
    - RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
  notify: restart httpd

- name: enable httpd
  service:
    name: httpd
    state: started
    enabled: true
