- name: ensure keystore directory exists
  file:
    path: "{{ jenkins_home }}/.ssl"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy in ssl files
  copy:
    src: "{{ item.in }}"
    dest: "{{ jenkins_home }}/.ssl/{{ item.out }}"
    owner: jenkins
    group: jenkins
    mode: 0755
  with_items:
    - in: "{{ jenkins_ssl_cert }}"
      out: jenkins.crt
    - in: "{{ jenkins_ssl_key }}"
      out: jenkins.key
  when: jenkins_ssl_cert is defined and jenkins_ssl_key is defined
  notify: restart Jenkins

- name: copy ssl certificate to anchors
  copy:
    src: "{{ (jenkins_ssl_cert is defined) | ternary('{{ jenkins_home }}/.ssl/jenkins.crt',
    '/etc/nginx/conf.d/ssl.pem') }}"
    dest: /etc/pki/ca-trust/source/anchors/jenkins.crt
    owner: root
    group: root
    remote_src: true
  notify: update certificate chains

- name: force SSL updates already
  meta: flush_handlers
