- name: ensure firewalld is installed
  package:
    name: firewalld
    state: present
  become: true

- name: ensure firewalld is disabled
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: set iptables to allow established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: "000 accept related established rules"

- name: set iptables to accept all icmp
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
    comment: "001 accept all icmp"

- name: set iptables to accept all communication from lo interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: "002 accept all to lo interface"

- name: set iptables to reject other communication to localhost
  iptables:
    chain: INPUT
    destination: 127.0.0.1/8
    reject_with: icmp-port-unreachable
    comment: "003 reject local traffic not on loopback interface"

- name: set iptables to allow Jenkins-related TCP ports
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    protocol: tcp
    jump: ACCEPT
  with_items: "{{ firewall_tcp_ports }}"

- name: set iptables rules forwarding port to Jenkins default port
  iptables:
    chain: PREROUTING
    destination_port: "{{ https_enabled | ternary(443, 80) }}"
    protocol: tcp
    table: nat
    match: tcp
    jump: REDIRECT
    to_ports: "{{ https_enabled | ternary(8443, 8080) }}"
    state: present
    comment: "901 forward 80/443 to Jenkins default port"
  register: remote_port_forward

- name: set iptables rule forwarding loopback to Jenkins default port
  iptables:
    chain: OUTPUT
    table: nat
    source: 0/0
    destination: 127.0.0.1
    protocol: tcp
    destination_port: "{{ https_enabled | ternary(443, 80) }}"
    jump: REDIRECT
    to_ports: "{{ https_enabled | ternary(8443, 8080) }}"
    state: present
    comment: "902 forward 80/443 to Jenkins default port on loopback"
    # action: insert - avaialble in Ansible 2.2+
  register: local_port_forward

- name: set iptables rule forwarding for real address to loopback
  iptables:
    chain: OUTPUT
    table: nat
    protocol: tcp
    destination: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    destination_port: "{{ https_enabled | ternary(443, 80) }}"
    jump: REDIRECT
    to_ports: "{{ https_enabled | ternary(8443, 8080) }}"
    state: present
  register: output_port_forward

- name: set iptables to reject all other connections
  iptables:
    chain: INPUT
    protocol: all
    reject_with: icmp-admin-prohibited
    comment: "999 Reject all other communication"

- name: save iptables
  command: service iptables save
  when: >-
    (remote_port_forward|changed) or
    (local_port_forward|changed) or
    (output_port_forward|changed)
  tags:
    - skip_ansible_lint

- name: start iptables
  service:
    name: iptables
    state: started
