- name: ensure firewalld is installed
  package:
    name: firewalld
    state: present
  become: true

- name: ensure firewalld is disabled
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: set iptables to allow established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: "000 accept related established rules"
  notify: save iptables

- name: set iptables to accept all icmp
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
    comment: "001 accept all icmp"
  notify: save iptables

- name: set iptables to accept all communication from lo interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: "002 accept all to lo interface"
  notify: save iptables

- name: set iptables to reject other communication to localhost
  iptables:
    chain: INPUT
    destination: 127.0.0.1/8
    reject_with: icmp-port-unreachable
    comment: "003 reject local traffic not on loopback interface"
  notify: save iptables

- name: set iptables to allow Jenkins-related TCP ports
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    protocol: tcp
    jump: ACCEPT
  with_items: "{{ firewall_tcp_ports }}"
  when: item is defined
  notify: save iptables

- name: set iptables to reject all other connections
  iptables:
    chain: INPUT
    protocol: all
    reject_with: icmp-admin-prohibited
    comment: "999 Reject all other communication"
  notify: save iptables

- name: flush handlers
  meta: flush_handlers

- name: start iptables
  service:
    name: iptables
    state: started
