- name: install beaker client
  yum:
    name: libxslt-python,beaker-client
    state: present
  when: install_beaker

- name: install java
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.{{ java_version }}.0-openjdk
    - java-1.{{ java_version }}.0-openjdk-devel

- name: upload common requirements file
  copy:
    src: requirements-common.txt
    dest: /tmp/requirements-common.txt
