- name: enable selinux overrides
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_can_sendmail
