- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: update certificate chains
  command: /usr/bin/update-ca-trust extract

- name: restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: reload firewalld
  command: firewall-cmd --reload
  tags:
    - skip_ansible_lint
